// Code generated by openapi-generator (-g wso2-mcp). DO NOT EDIT.
//
// An MCP server over the WSO2 Identity Server API, spoken on stdin and
// stdout. NOTHING may be written to stdout that is not a protocol message --
// a stray print is a parse error at the client, so every diagnostic here goes
// to stderr.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/n-at-han-k/mcp-server-wso2/internal/wso2"
)

// This server's version, not the API document's: the documents say
// "v1", which is the API version and moves for reasons that have nothing
// to do with this binary.
const version = "1.0.0"

func main() {
	log.SetOutput(os.Stderr)
	log.SetFlags(0)

	baseURL := os.Getenv("WSO2_BASE_URL")
	if baseURL == "" {
		log.Fatal("WSO2_BASE_URL is not set: it is the server and the API prefix, " +
			"e.g. https://is.example.com/api/server/v1 or " +
			"https://is.example.com/t/carbon.super/api/server/v1")
	}

	client := wso2.NewClient(baseURL, os.Getenv("WSO2_INSECURE") == "true")
	client.Token = os.Getenv("WSO2_TOKEN")
	client.Username = os.Getenv("WSO2_USERNAME")
	client.Password = os.Getenv("WSO2_PASSWORD")

	if client.Token == "" && client.Username == "" {
		log.Print("neither WSO2_TOKEN nor WSO2_USERNAME is set: every call will be unauthenticated")
	}

	server := mcp.NewServer(&mcp.Implementation{
		Name:    "mcp-server-wso2",
		Version: version,
	}, nil)

	for _, tool := range wso2.Tools {
		// The loop variable is captured by the handler, and the table is
		// walked long before any of them run.
		tool := tool

		// Server.AddTool, not mcp.AddTool: the generic one infers a schema
		// from a Go type, and these schemas came out of the document. The SDK
		// then does no argument validation, so the client does its own.
		server.AddTool(&mcp.Tool{
			Name:        tool.Name,
			Description: tool.Description,
			InputSchema: tool.Schema,
		}, func(ctx context.Context, request *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return call(ctx, client, tool, request)
		})
	}

	if err := server.Run(context.Background(), &mcp.StdioTransport{}); err != nil {
		log.Fatal(err)
	}
}

// call runs one tool and answers what the server said.
//
// A REFUSAL FROM WSO2 IS A RESULT, NOT A TRANSPORT ERROR. Returned as an
// error, it reaches the model as "the tool is broken"; returned as a result
// with IsError, the model reads the status and the body and can act on them --
// a 409 on a create means it is already there.
func call(ctx context.Context, client *wso2.Client, tool wso2.Tool, request *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	args := map[string]json.RawMessage{}

	if raw := request.Params.Arguments; len(raw) > 0 {
		if err := json.Unmarshal(raw, &args); err != nil {
			return errorResult(fmt.Sprintf("arguments are not a JSON object: %v", err)), nil
		}
	}

	body, err := client.Call(ctx, tool, args)
	if err != nil {
		return errorResult(err.Error()), nil
	}

	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: body}},
	}, nil
}

func errorResult(text string) *mcp.CallToolResult {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{&mcp.TextContent{Text: text}},
	}
}
