// Code generated by openapi-generator (-g wso2-mcp). DO NOT EDIT.
package wso2

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// APIError is any answer that was not a 2xx, carrying the status alongside the
// body.
//
// THE STATUS IS WHAT A MODEL NEEDS TO DECIDE WHAT TO DO NEXT. A 404 on a read
// means the thing is not there and the next step is to create it; a 500 means
// nothing of the kind. Collapsed into "an error", both read as "try again".
type APIError struct {
	StatusCode int
	Body       string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("API error (status %d): %s", e.StatusCode, e.Body)
}

// Client talks to one WSO2 Identity Server.
//
// The tenant API is super-tenant scoped (/api/server/v1/tenants) and the
// organization API is tenant scoped (/t/{tenant-domain}/api/server/v1). One
// client holds one base URL, so reaching both means running this server twice.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	Token      string
	Username   string
	Password   string
}

// NewClient creates a client for the given base URL. insecure skips
// certificate verification, which a WSO2 running on its own self-signed
// certificate needs and nothing else should.
func NewClient(baseURL string, insecure bool) *Client {
	httpClient := &http.Client{}

	if insecure {
		httpClient.Transport = &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, // #nosec G402 -- opt-in, see WSO2_INSECURE
		}
	}

	return &Client{BaseURL: strings.TrimRight(baseURL, "/"), HTTPClient: httpClient}
}

// Call runs one tool: the path template filled from args, the query attached,
// the body sent. The answer is returned as it arrived -- an MCP tool result is
// text, and the model reads JSON.
func (c *Client) Call(ctx context.Context, tool Tool, args map[string]json.RawMessage) (string, error) {
	path := tool.Path

	for _, name := range tool.PathParams {
		raw, ok := args[name]
		if !ok {
			return "", fmt.Errorf("%s: missing required argument %q", tool.Name, name)
		}

		// A path parameter is a URL segment, so a tenant domain with a slash
		// in it must not silently become two segments.
		path = strings.ReplaceAll(path, "{"+name+"}", url.PathEscape(scalar(raw)))
	}

	query := url.Values{}
	for _, name := range tool.QueryParams {
		if raw, ok := args[name]; ok {
			query.Set(name, scalar(raw))
		}
	}

	if len(query) > 0 {
		path += "?" + query.Encode()
	}

	var reqBody io.Reader
	body, hasBody := args["body"]

	if tool.HasBody && hasBody {
		reqBody = bytes.NewReader(body)
	}

	req, err := http.NewRequestWithContext(ctx, tool.Method, c.BaseURL+path, reqBody)
	if err != nil {
		return "", fmt.Errorf("error creating request: %w", err)
	}

	if reqBody != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("Accept", "application/json")

	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	} else if c.Username != "" {
		req.SetBasicAuth(c.Username, c.Password)
	}

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("error making request: %w", err)
	}
	defer resp.Body.Close() //nolint:errcheck

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("error reading response body: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", &APIError{StatusCode: resp.StatusCode, Body: string(respBody)}
	}

	// A 204, and a create that answers nothing but a Location header. Saying
	// nothing back reads as a failure; the header is where the new identifier
	// is.
	if len(bytes.TrimSpace(respBody)) == 0 {
		if location := resp.Header.Get("Location"); location != "" {
			return fmt.Sprintf(`{"status":%d,"location":%q}`, resp.StatusCode, location), nil
		}

		return fmt.Sprintf(`{"status":%d}`, resp.StatusCode), nil
	}

	return string(respBody), nil
}

// scalar spells an argument the way a URL takes it. A JSON string arrives
// quoted, and "limit=\"10\"" is not a number WSO2 will accept -- everything
// else is already its own text.
func scalar(raw json.RawMessage) string {
	var text string
	if err := json.Unmarshal(raw, &text); err == nil {
		return text
	}

	return string(raw)
}
