// Code generated by openapi-generator (-g wso2-mcp). DO NOT EDIT.
//
// What every one of the generated tools is dispatched through: the path
// template filled, the query attached, the body sent, the status kept.
package wso2

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func args(pairs map[string]string) map[string]json.RawMessage {
	out := map[string]json.RawMessage{}
	for key, value := range pairs {
		out[key] = json.RawMessage(value)
	}

	return out
}

func TestCallFillsPathQueryAndBody(t *testing.T) {
	var seen *http.Request
	var body string

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seen = r
		raw, _ := io.ReadAll(r.Body)
		body = string(raw)
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"id":"abc"}`))
	}))
	defer server.Close()

	tool := Tool{
		Name:        "update_organization",
		Method:      "PUT",
		Path:        "/organizations/{organization-id}",
		PathParams:  []string{"organization-id"},
		QueryParams: []string{"limit", "filter"},
		HasBody:     true,
	}

	out, err := NewClient(server.URL, false).Call(context.Background(), tool, args(map[string]string{
		"organization-id": `"o/1"`,
		"limit":           `10`,
		"body":            `{"name":"acme"}`,
	}))
	if err != nil {
		t.Fatalf("Call: %v", err)
	}

	// A path parameter is one segment: "o/1" must not become two.
	if seen.URL.EscapedPath() != "/organizations/o%2F1" {
		t.Errorf("path = %q", seen.URL.EscapedPath())
	}
	// A number is not quoted on its way into a query string, and a query
	// parameter nobody passed is not sent empty.
	if seen.URL.RawQuery != "limit=10" {
		t.Errorf("query = %q", seen.URL.RawQuery)
	}
	if body != `{"name":"acme"}` {
		t.Errorf("body = %q", body)
	}
	if out != `{"id":"abc"}` {
		t.Errorf("result = %q", out)
	}
}

func TestCallKeepsTheStatus(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNotFound)
		_, _ = w.Write([]byte(`{"code":"ORG-60002"}`))
	}))
	defer server.Close()

	_, err := NewClient(server.URL, false).Call(context.Background(),
		Tool{Name: "get_organization", Method: "GET", Path: "/organizations/x"}, nil)

	apiErr, ok := err.(*APIError)
	if !ok {
		t.Fatalf("error = %v, want *APIError", err)
	}
	// 404 means gone and 500 means broken; a model cannot tell them apart
	// from "an error".
	if apiErr.StatusCode != http.StatusNotFound || !strings.Contains(apiErr.Body, "ORG-60002") {
		t.Errorf("APIError = %+v", apiErr)
	}
}

func TestCallAnswersACreateWithNoBody(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Location", "https://is.example.com/api/server/v1/applications/7")
		w.WriteHeader(http.StatusCreated)
	}))
	defer server.Close()

	// WSO2 answers a create with 201 and nothing at all; the identifier is in
	// the header, and saying nothing back reads as a failure.
	out, err := NewClient(server.URL, false).Call(context.Background(),
		Tool{Name: "create_application", Method: "POST", Path: "/applications", HasBody: true},
		args(map[string]string{"body": `{"name":"acme"}`}))
	if err != nil {
		t.Fatalf("Call: %v", err)
	}
	if !strings.Contains(out, "/applications/7") || !strings.Contains(out, "201") {
		t.Errorf("result = %q", out)
	}
}

func TestCallRefusesAMissingPathParam(t *testing.T) {
	// No request is possible, and an unfilled "{organization-id}" in the URL
	// would 404 somewhere far from the cause.
	_, err := NewClient("https://is.example.com", false).Call(context.Background(),
		Tool{Name: "get_organization", Method: "GET", Path: "/organizations/{organization-id}",
			PathParams: []string{"organization-id"}}, nil)

	if err == nil || !strings.Contains(err.Error(), "organization-id") {
		t.Errorf("err = %v", err)
	}
}

func TestEveryToolHasAnObjectSchema(t *testing.T) {
	if len(Tools) == 0 {
		t.Fatal("no tools generated")
	}

	seen := map[string]bool{}

	for _, tool := range Tools {
		// A duplicate name silently shadows a tool at the client.
		if seen[tool.Name] {
			t.Errorf("duplicate tool name %q", tool.Name)
		}
		seen[tool.Name] = true

		var schema struct {
			Type       string                     `json:"type"`
			Properties map[string]json.RawMessage `json:"properties"`
		}
		if err := json.Unmarshal(tool.Schema, &schema); err != nil {
			t.Errorf("%s: schema is not JSON: %v", tool.Name, err)
			continue
		}
		if schema.Type != "object" {
			t.Errorf("%s: schema type = %q", tool.Name, schema.Type)
		}
		// Every path parameter has to be declarable, or the tool cannot be
		// called at all.
		for _, name := range tool.PathParams {
			if _, ok := schema.Properties[name]; !ok {
				t.Errorf("%s: path param %q is not in the schema", tool.Name, name)
			}
		}
	}
}
